/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.jus.trt14.gui.dialogs;

import br.jus.trt14.tools.Utils;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class DialogChooseCertificate extends DialogBasico {

    /**
     * Creates new form DialogChooseCertificate
     */
    public String selectedAlias = "";

    public DialogChooseCertificate(List<Object[]> certificates) {
        initComponents();
        this.setLocationRelativeTo(null);
        constructTableCertificate(certificates);
    }

    private void constructTableCertificate(List<Object[]> certificates) {
        if (certificates.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não consegui obter a lista de certificados!\nPor favor, verifique se o seu certificado está inserido corretamente!\n"
                    + "Caso ainda esteja tendo problemas experimente acessar o serviço e-CAC da Receita Federal");
            try {
                URL url = new URL("https://cav.receita.fazenda.gov.br/eCAC/publico/login.aspx");
                Utils.openWebpage(url.toURI());
            } catch (Exception ex) {
                Logger.getLogger(Atualizacao.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
            return;
        }
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTCertificado.getModel();
        for (Object[] obj : certificates) {
            Object[] extractCertificateInfo = Utils.extractCertificateInfo(obj);
            defaultTableModel.addRow(extractCertificateInfo);
        }
        jTCertificado.setRowSelectionInterval(0, 0);
        this.setVisible(true);
        this.setModal(true);
        Utils.detectEnterTableAction(jTCertificado, jBEscolherCertificado);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTCertificado = new javax.swing.JTable();
        jBEscolherCertificado = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLEmitirCertificado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Escolha o seu certificado digital");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTCertificado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Certificado", "Início", "Fim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCertificado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCertificadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCertificado);
        if (jTCertificado.getColumnModel().getColumnCount() > 0) {
            jTCertificado.getColumnModel().getColumn(1).setMinWidth(100);
            jTCertificado.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTCertificado.getColumnModel().getColumn(1).setMaxWidth(100);
            jTCertificado.getColumnModel().getColumn(2).setMinWidth(100);
            jTCertificado.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTCertificado.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jBEscolherCertificado.setText("Escolher");
        jBEscolherCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolherCertificadoActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLEmitirCertificado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEmitirCertificado.setForeground(new java.awt.Color(0, 102, 255));
        jLEmitirCertificado.setText("Gerenciar certificados");
        jLEmitirCertificado.setToolTipText("");
        jLEmitirCertificado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLEmitirCertificado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLEmitirCertificadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLEmitirCertificado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEscolherCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEscolherCertificado)
                    .addComponent(jBCancelar)
                    .addComponent(jLEmitirCertificado))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEscolherCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolherCertificadoActionPerformed

        DefaultTableModel defaultTableModel = (DefaultTableModel) jTCertificado.getModel();
        if (defaultTableModel.getRowCount() > 0) {
            int selectedRow = jTCertificado.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Você precisa escolher um certificado");
                return;
            }
            selectedAlias = defaultTableModel.getValueAt(selectedRow, 0).toString();
        } else {
            JOptionPane.showMessageDialog(null, "Não consegui obter a lista de certificados");
        }
        DialogChooseCertificate.this.dispatchEvent(new WindowEvent(
                DialogChooseCertificate.this, WindowEvent.WINDOW_CLOSING));


    }//GEN-LAST:event_jBEscolherCertificadoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        DialogChooseCertificate.this.dispatchEvent(new WindowEvent(
                DialogChooseCertificate.this, WindowEvent.WINDOW_CLOSING));

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //jBCancelar.doClick();
    }//GEN-LAST:event_formWindowClosed

    private void jTCertificadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCertificadoMouseClicked
        if (evt.getClickCount() == 2) {
            jBEscolherCertificado.doClick();
        }

    }//GEN-LAST:event_jTCertificadoMouseClicked

    private void jLEmitirCertificadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEmitirCertificadoMouseClicked
        try {
            JOptionPane.showMessageDialog(null, "Na tela a seguir clique em certificados");
            Runtime.getRuntime().exec("C:\\Windows\\System32\\control.exe inetcpl.cpl,,3");
        } catch (Exception ex) {
            Logger.getLogger(Atualizacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLEmitirCertificadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogChooseCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogChooseCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogChooseCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogChooseCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    public javax.swing.JButton jBEscolherCertificado;
    private javax.swing.JLabel jLEmitirCertificado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCertificado;
    // End of variables declaration//GEN-END:variables
}
