/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.jus.trt14.gui.dialogs;

import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * 
 */
public class ProcessandoAssinatura extends DialogBasico {

    /**
     * Creates new form ProcessandoAssinatura
     */
    public ProcessandoAssinatura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public ProcessandoAssinatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBProgresso = new javax.swing.JProgressBar();
        jLTextoAnalise = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Assinatura digital");
        setModal(true);
        setResizable(false);

        jPBProgresso.setStringPainted(true);

        jLTextoAnalise.setText("Verificando certificados revogados...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTextoAnalise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBProgresso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTextoAnalise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPBProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLTextoAnalise;
    private javax.swing.JProgressBar jPBProgresso;
    // End of variables declaration//GEN-END:variables

    public void iniciarDialog(int size) throws HeadlessException {
        final JDialog dialog = this;
        dialog.setLocationRelativeTo(null);
        jPBProgresso.setMinimum(0);
        jPBProgresso.setMaximum(size);
        new Thread(new Runnable() {
            @Override
            public void run() {
                dialog.setVisible(true);

            }
        }).start();
        while (!this.isVisible()) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(ProcessandoAssinatura.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void setValueProgressBar(int i) {
        jPBProgresso.setValue(i);
    }

    public void setText(String string) {
        jLTextoAnalise.setText(string);
    }

}
