/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.jus.trt14.gui;

import br.jus.trt14.gui.dialogs.TelaConvertendo;
import br.jus.trt14.tools.Archive;
import br.jus.trt14.tools.Utils;
import java.awt.FileDialog;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class Juntar extends FrameBasico {

    public static boolean assinarDigitalmente = false;

    /**
     * Creates new form TelaEntrada
     */
    public Juntar() {
        initComponents();
        this.position();
        super.setBasicEvents(jScrollPane1, jTblListaPDF, jLStatus);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLSuperior = new javax.swing.JLabel();
        jPEntrada = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblListaPDF = new javax.swing.JTable();
        jLblTextoSelecionePDF = new javax.swing.JLabel();
        jBAbrirDocumentoPDFEntrada = new javax.swing.JButton();
        jBExcluirItemLista = new javax.swing.JButton();
        jBDescerOrdemItemLista = new javax.swing.JButton();
        jBSubirOrdemItemLista = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBJuntar = new javax.swing.JButton();
        jPSaida = new javax.swing.JPanel();
        jTFSaidaPath = new javax.swing.JTextField();
        jLSaidaInforme = new javax.swing.JLabel();
        jBLocalArmazenamentoArquivoSaida = new javax.swing.JButton();
        jPSaida1 = new javax.swing.JPanel();
        jCAssinarDigitalmente = new javax.swing.JCheckBox();
        jLStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JT - Otimizador PDF");

        jLSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trt14_logo_small.png"))); // NOI18N
        jLSuperior.setAlignmentX(0.5F);

        jPEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Juntar Documentos"));

        jTblListaPDF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caminho", "Páginas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblListaPDF.setToolTipText("<html>Você pode arrastar e soltar documentos <b>()</b> para essa tabela.<br>Clique duplo abre o arquivo selecionado</html>");
        jTblListaPDF.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTblListaPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblListaPDFMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTblListaPDFMouseReleased(evt);
            }
        });
        jTblListaPDF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTblListaPDFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTblListaPDFFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTblListaPDF);
        if (jTblListaPDF.getColumnModel().getColumnCount() > 0) {
            jTblListaPDF.getColumnModel().getColumn(1).setMinWidth(45);
            jTblListaPDF.getColumnModel().getColumn(1).setMaxWidth(55);
        }

        jLblTextoSelecionePDF.setText("Selecione (ou arraste e solte) os arquivos. Os documentos adicionados são convertidos em PDF/A automaticamente");

        jBAbrirDocumentoPDFEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome_folder_open_16.png"))); // NOI18N
        jBAbrirDocumentoPDFEntrada.setText("Incluir");
        jBAbrirDocumentoPDFEntrada.setMaximumSize(new java.awt.Dimension(100, 25));
        jBAbrirDocumentoPDFEntrada.setMinimumSize(new java.awt.Dimension(100, 25));
        jBAbrirDocumentoPDFEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirDocumentoPDFEntradaActionPerformed(evt);
            }
        });

        jBExcluirItemLista.setText("Excluir PDF");
        jBExcluirItemLista.setEnabled(false);
        jBExcluirItemLista.setMaximumSize(new java.awt.Dimension(100, 23));
        jBExcluirItemLista.setMinimumSize(new java.awt.Dimension(100, 23));
        jBExcluirItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirItemListaActionPerformed(evt);
            }
        });

        jBDescerOrdemItemLista.setText("↓");
        jBDescerOrdemItemLista.setEnabled(false);
        jBDescerOrdemItemLista.setMaximumSize(new java.awt.Dimension(100, 23));
        jBDescerOrdemItemLista.setMinimumSize(new java.awt.Dimension(100, 23));
        jBDescerOrdemItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescerOrdemItemListaActionPerformed(evt);
            }
        });

        jBSubirOrdemItemLista.setText("↑");
        jBSubirOrdemItemLista.setEnabled(false);
        jBSubirOrdemItemLista.setMaximumSize(new java.awt.Dimension(100, 23));
        jBSubirOrdemItemLista.setMinimumSize(new java.awt.Dimension(100, 23));
        jBSubirOrdemItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubirOrdemItemListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEntradaLayout = new javax.swing.GroupLayout(jPEntrada);
        jPEntrada.setLayout(jPEntradaLayout);
        jPEntradaLayout.setHorizontalGroup(
            jPEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addGroup(jPEntradaLayout.createSequentialGroup()
                        .addComponent(jLblTextoSelecionePDF)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPEntradaLayout.createSequentialGroup()
                        .addComponent(jBAbrirDocumentoPDFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBExcluirItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSubirOrdemItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDescerOrdemItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPEntradaLayout.setVerticalGroup(
            jPEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntradaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLblTextoSelecionePDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluirItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAbrirDocumentoPDFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDescerOrdemItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSubirOrdemItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Otimizador");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("PDF");

        jBJuntar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doc_convert.png"))); // NOI18N
        jBJuntar.setText("Juntar PDFs");
        jBJuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBJuntarActionPerformed(evt);
            }
        });

        jPSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída"));

        jTFSaidaPath.setEditable(false);

        jLSaidaInforme.setText("Informe o local onde deseja salvar o arquivo convertido.");

        jBLocalArmazenamentoArquivoSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome_folder_open_16.png"))); // NOI18N
        jBLocalArmazenamentoArquivoSaida.setText("Abrir");
        jBLocalArmazenamentoArquivoSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLocalArmazenamentoArquivoSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSaidaLayout = new javax.swing.GroupLayout(jPSaida);
        jPSaida.setLayout(jPSaidaLayout);
        jPSaidaLayout.setHorizontalGroup(
            jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSaidaInforme, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jTFSaidaPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBLocalArmazenamentoArquivoSaida)
                .addGap(136, 136, 136))
        );
        jPSaidaLayout.setVerticalGroup(
            jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaidaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLSaidaInforme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSaidaPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLocalArmazenamentoArquivoSaida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPSaida1.setBorder(javax.swing.BorderFactory.createTitledBorder("Assinatura digital"));

        jCAssinarDigitalmente.setText("Assinar digitalmente a saída");
        jCAssinarDigitalmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAssinarDigitalmenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSaida1Layout = new javax.swing.GroupLayout(jPSaida1);
        jPSaida1.setLayout(jPSaida1Layout);
        jPSaida1Layout.setHorizontalGroup(
            jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaida1Layout.createSequentialGroup()
                .addComponent(jCAssinarDigitalmente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPSaida1Layout.setVerticalGroup(
            jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaida1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCAssinarDigitalmente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading.gif")));
        jLStatus.setText("  ");
        jLStatus.setToolTipText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPSaida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBJuntar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPSaida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBJuntar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAbrirDocumentoPDFEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirDocumentoPDFEntradaActionPerformed
        addFile(jTblListaPDF, jLStatus);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jBAbrirDocumentoPDFEntradaActionPerformed

    private void jBJuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBJuntarActionPerformed
        if (jTblListaPDF.getRowCount() > 1) {
            if (!jTFSaidaPath.getText().isEmpty()) {
                boolean erro = false;
                int rowCount = jTblListaPDF.getRowCount();
                List<String> listaArquivos = new ArrayList<String>();
                for (int i = 0; i < rowCount; i++) {
                    String fileName = (String) jTblListaPDF.getValueAt(i, 0);
                    File file = new File(Utils.getRandomFileName());
                    Archive.copy(new File(fileName), file);
                    listaArquivos.add(file.getAbsolutePath());
                    if (fileName.equals(jTFSaidaPath.getText())) {
                        erro = true;
                        break;
                    }
                }

                if (erro) {
                    JOptionPane.showMessageDialog(null, "Por favor, o arquivo de saída não pode ser o mesmo de origem!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    TelaConvertendo telaConvertendo = new TelaConvertendo();
                    telaConvertendo.iniciarDialog(listaArquivos, jTFSaidaPath.getText(), this);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Por favor, selecione o local onde deseja salvar o arquivo convertido", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione pelo menos 2 arquivos", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBJuntarActionPerformed

    private void jTblListaPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblListaPDFMouseClicked
        jTblListaPDFFocusGained(null);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jTblListaPDFMouseClicked

    private void jTblListaPDFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblListaPDFFocusGained
        controlarBotaoExcluir(jTblListaPDF, jBExcluirItemLista);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jTblListaPDFFocusGained

    private void jBExcluirItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirItemListaActionPerformed
        excluirDocumentoPDF(jTblListaPDF);
        jTblListaPDFFocusGained(null);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jBExcluirItemListaActionPerformed

    private void jTblListaPDFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblListaPDFFocusLost
        jTblListaPDFFocusGained(evt);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jTblListaPDFFocusLost

    private void jBLocalArmazenamentoArquivoSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLocalArmazenamentoArquivoSaidaActionPerformed
        String diretorio = ".";
        if (jTblListaPDF.getModel().getRowCount() > 0) {
            diretorio = (String) jTblListaPDF.getModel().getValueAt(0, 0);
        }
        JFileChooser fc = new JFileChooser();
        FileFilter ff = new FileNameExtensionFilter("PDF (Portable Document Format)", "pdf");
        fc.setFileFilter(ff);
        fc.setAcceptAllFileFilterUsed(false);
        fc.setCurrentDirectory(new File(diretorio));
        int opt = fc.showSaveDialog(this);
        File f = fc.getSelectedFile();
        if (opt == 0) {
            jTFSaidaPath.setText(f.getPath().replace(".pdf", "") + ".pdf");
        }
    }//GEN-LAST:event_jBLocalArmazenamentoArquivoSaidaActionPerformed

    private void jBDescerOrdemItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescerOrdemItemListaActionPerformed
        down(jTblListaPDF, jBDescerOrdemItemLista, jBSubirOrdemItemLista);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jBDescerOrdemItemListaActionPerformed

    private void jBSubirOrdemItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubirOrdemItemListaActionPerformed
        up(jTblListaPDF, jBDescerOrdemItemLista, jBSubirOrdemItemLista);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jBSubirOrdemItemListaActionPerformed

    private void jTblListaPDFMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblListaPDFMouseReleased
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jTblListaPDFMouseReleased

    private void jCAssinarDigitalmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAssinarDigitalmenteActionPerformed
        assinarDigitalmente = ((JCheckBox) evt.getSource()).isSelected();
    }//GEN-LAST:event_jCAssinarDigitalmenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juntar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juntar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juntar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juntar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juntar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbrirDocumentoPDFEntrada;
    private javax.swing.JButton jBDescerOrdemItemLista;
    private javax.swing.JButton jBExcluirItemLista;
    private javax.swing.JButton jBJuntar;
    private javax.swing.JButton jBLocalArmazenamentoArquivoSaida;
    private javax.swing.JButton jBSubirOrdemItemLista;
    private javax.swing.JCheckBox jCAssinarDigitalmente;
    private javax.swing.JLabel jLSaidaInforme;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLSuperior;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblTextoSelecionePDF;
    private javax.swing.JPanel jPEntrada;
    private javax.swing.JPanel jPSaida;
    private javax.swing.JPanel jPSaida1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFSaidaPath;
    private javax.swing.JTable jTblListaPDF;
    // End of variables declaration//GEN-END:variables

    void iniciarArgumentos(String saida, List<String> listaArquivos) {
        jTFSaidaPath.setText(saida);
        for (String arq : listaArquivos) {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel = (DefaultTableModel) jTblListaPDF.getModel();
            String pageCount = String.valueOf(Utils.getPageCount(arq));
            if (!pageCount.equals("0")) {
                tableModel.addRow(new Object[]{arq, pageCount});
            }
        }
        this.setVisible(true);

    }

}
