/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.jus.trt14.gui;

import br.jus.trt14.constant.Constant;
import br.jus.trt14.converter.Converter;
import br.jus.trt14.converter.NiveisCompactacao;
import br.jus.trt14.job.ThreadConverter;
import br.jus.trt14.tools.Preferences;
import br.jus.trt14.tools.Utils;
import java.awt.Color;
import java.awt.FileDialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class OtimizarLote extends FrameBasico {

    private ExecutorService executor;

    /**
     * Creates new form TelaEntrada
     */
    public OtimizarLote() {
        initComponents();
        this.position();
        jTFSaidaPath.setVisible(false);
        jLSaidaInforme.setVisible(false);
        jBCancelar1.setVisible(false);
        jTFTamanhoArquivo.setVisible(false);
        jLTamanhoArquivo1.setVisible(false);
        jBLocalArmazenamentoArquivoSaida.setVisible(false);
        executor = Executors.newFixedThreadPool(1);
        setPreferencias();

        super.setBasicEvents(jScrollPane1, jTblListaPDF, jLStatus);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroupTipoSaida = new javax.swing.ButtonGroup();
        jLSuperior = new javax.swing.JLabel();
        jPEntrada = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblListaPDF = new javax.swing.JTable();
        jLblTextoSelecionePDF = new javax.swing.JLabel();
        jBAbrirDocumentoPDFEntrada = new javax.swing.JButton();
        jBExcluirItemLista = new javax.swing.JButton();
        jBDescerOrdemItemLista = new javax.swing.JButton();
        jBSubirOrdemItemLista = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBJuntar = new javax.swing.JButton();
        jPSaida = new javax.swing.JPanel();
        jTFSaidaPath = new javax.swing.JTextField();
        jLSaidaInforme = new javax.swing.JLabel();
        jBLocalArmazenamentoArquivoSaida = new javax.swing.JButton();
        jRBSalvarPastaSeparada = new javax.swing.JRadioButton();
        jRBSalvaDestinoInformado = new javax.swing.JRadioButton();
        jPSaida1 = new javax.swing.JPanel();
        jLOpcoesNivel = new javax.swing.JLabel();
        jLOpcoesFinalidade = new javax.swing.JLabel();
        jCBCompactacao = new javax.swing.JComboBox();
        jCBFinalidade = new javax.swing.JComboBox();
        jLAjudaCompactacao = new javax.swing.JLabel();
        jLAjudaConversao = new javax.swing.JLabel();
        jTFTamanhoArquivo = new javax.swing.JTextField();
        jLTamanhoArquivo1 = new javax.swing.JLabel();
        jPBProgresso = new javax.swing.JProgressBar();
        jBCancelar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLArquivos = new javax.swing.JLabel();
        jLStatus1 = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JT - Otimizador PDF");

        jLSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trt14_logo_small.png"))); // NOI18N
        jLSuperior.setAlignmentX(0.5F);

        jPEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Otimizar em Lote"));

        jTblListaPDF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caminho", "Páginas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblListaPDF.setToolTipText("<html>Você pode arrastar e soltar documentos <b>()</b> para essa tabela.<br>Clique duplo abre o arquivo selecionado</html>");
        jTblListaPDF.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTblListaPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblListaPDFMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTblListaPDFMouseReleased(evt);
            }
        });
        jTblListaPDF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTblListaPDFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTblListaPDFFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTblListaPDF);
        if (jTblListaPDF.getColumnModel().getColumnCount() > 0) {
            jTblListaPDF.getColumnModel().getColumn(1).setMinWidth(45);
            jTblListaPDF.getColumnModel().getColumn(1).setMaxWidth(55);
        }

        jLblTextoSelecionePDF.setText("Selecione (ou arraste e solte) os arquivos. Os documentos adicionados são convertidos em PDF/A automaticamente");

        jBAbrirDocumentoPDFEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome_folder_open_16.png"))); // NOI18N
        jBAbrirDocumentoPDFEntrada.setText("Incluir");
        jBAbrirDocumentoPDFEntrada.setMaximumSize(new java.awt.Dimension(100, 25));
        jBAbrirDocumentoPDFEntrada.setMinimumSize(new java.awt.Dimension(100, 25));
        jBAbrirDocumentoPDFEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirDocumentoPDFEntradaActionPerformed(evt);
            }
        });

        jBExcluirItemLista.setText("Excluir PDF");
        jBExcluirItemLista.setEnabled(false);
        jBExcluirItemLista.setMaximumSize(new java.awt.Dimension(100, 23));
        jBExcluirItemLista.setMinimumSize(new java.awt.Dimension(100, 23));
        jBExcluirItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirItemListaActionPerformed(evt);
            }
        });

        jBDescerOrdemItemLista.setText("↓");
        jBDescerOrdemItemLista.setEnabled(false);
        jBDescerOrdemItemLista.setMaximumSize(new java.awt.Dimension(100, 23));
        jBDescerOrdemItemLista.setMinimumSize(new java.awt.Dimension(100, 23));
        jBDescerOrdemItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescerOrdemItemListaActionPerformed(evt);
            }
        });

        jBSubirOrdemItemLista.setText("↑");
        jBSubirOrdemItemLista.setEnabled(false);
        jBSubirOrdemItemLista.setMaximumSize(new java.awt.Dimension(100, 23));
        jBSubirOrdemItemLista.setMinimumSize(new java.awt.Dimension(100, 23));
        jBSubirOrdemItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubirOrdemItemListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEntradaLayout = new javax.swing.GroupLayout(jPEntrada);
        jPEntrada.setLayout(jPEntradaLayout);
        jPEntradaLayout.setHorizontalGroup(
            jPEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(jPEntradaLayout.createSequentialGroup()
                        .addComponent(jLblTextoSelecionePDF)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPEntradaLayout.createSequentialGroup()
                        .addComponent(jBAbrirDocumentoPDFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBExcluirItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSubirOrdemItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDescerOrdemItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPEntradaLayout.setVerticalGroup(
            jPEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntradaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLblTextoSelecionePDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluirItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAbrirDocumentoPDFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDescerOrdemItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSubirOrdemItemLista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Otimizador");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("PDF");

        jBJuntar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doc_convert.png"))); // NOI18N
        jBJuntar.setText("Otimizar PDFs");
        jBJuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBJuntarActionPerformed(evt);
            }
        });

        jPSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída"));

        jTFSaidaPath.setEditable(false);

        jLSaidaInforme.setText("Informe o local onde deseja salvar os arquivos convertidos.");

        jBLocalArmazenamentoArquivoSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome_folder_open_16.png"))); // NOI18N
        jBLocalArmazenamentoArquivoSaida.setText("Abrir");
        jBLocalArmazenamentoArquivoSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLocalArmazenamentoArquivoSaidaActionPerformed(evt);
            }
        });

        bgroupTipoSaida.add(jRBSalvarPastaSeparada);
        jRBSalvarPastaSeparada.setSelected(true);
        jRBSalvarPastaSeparada.setText("Salvar os arquivos cada um em uma pasta separada.");
        jRBSalvarPastaSeparada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSalvarPastaSeparadaActionPerformed(evt);
            }
        });

        bgroupTipoSaida.add(jRBSalvaDestinoInformado);
        jRBSalvaDestinoInformado.setText("Salvar todos os arquivos no destino informado abaixo:");
        jRBSalvaDestinoInformado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSalvaDestinoInformadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSaidaLayout = new javax.swing.GroupLayout(jPSaida);
        jPSaida.setLayout(jPSaidaLayout);
        jPSaidaLayout.setHorizontalGroup(
            jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaidaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBSalvaDestinoInformado)
                    .addComponent(jRBSalvarPastaSeparada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSaidaInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPSaidaLayout.createSequentialGroup()
                        .addComponent(jTFSaidaPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBLocalArmazenamentoArquivoSaida)))
                .addContainerGap())
        );
        jPSaidaLayout.setVerticalGroup(
            jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSaidaLayout.createSequentialGroup()
                .addComponent(jRBSalvarPastaSeparada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBSalvaDestinoInformado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSaidaInforme)
                .addGap(1, 1, 1)
                .addGroup(jPSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSaidaPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLocalArmazenamentoArquivoSaida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPSaida1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jLOpcoesNivel.setText("Nível de Compactação:");

        jLOpcoesFinalidade.setText("Finalidade da Conversão:");

        jCBCompactacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Extrema", "Boa", "Razoável", "Mínima" }));
        jCBCompactacao.setSelectedIndex(2);
        jCBCompactacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCompactacaoActionPerformed(evt);
            }
        });

        jCBFinalidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PJE", "Proad", "Personalizado", "Não Dividir" }));
        jCBFinalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFinalidadeActionPerformed(evt);
            }
        });

        jLAjudaCompactacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome_dialog_question_20.png"))); // NOI18N
        jLAjudaCompactacao.setToolTipText("<html>\n<b>Defina o nível aplicado de compactação </b><br/>\n - Extrema: %sdpi - Maior compactação, pior qualidade. <br/>\n - Boa: %sdpi <br/>\n - Razoável: %sdpi <br/>\n - Mínima: %sdpi - Menor compactação, melhor qualidade. <br/>\nNão existe um padrão, varia de acordo com o conteúdo no arquivo. <br/>\nNão esqueça de verificar a legibilidade do arquivo gerado.\n</html>");
        jLAjudaCompactacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAjudaCompactacaoMouseClicked(evt);
            }
        });

        jLAjudaConversao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome_dialog_question_20.png"))); // NOI18N
        jLAjudaConversao.setToolTipText("<html>\n<b>A finalidade da conversão irá definir o tamanho dos arquivos gerados</b><br/>\n - PJE: Procura dividir os arquivos convertidos em 1,5 MB <br/>\n - Proad: Procura dividir os arquivos em blocos de 5 MB <br/>\n - Não Dividir: Não divide os arquivos convertidos <br/>\n</html>");

        jTFTamanhoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTamanhoArquivoActionPerformed(evt);
            }
        });

        jLTamanhoArquivo1.setText("MB(s)");

        javax.swing.GroupLayout jPSaida1Layout = new javax.swing.GroupLayout(jPSaida1);
        jPSaida1.setLayout(jPSaida1Layout);
        jPSaida1Layout.setHorizontalGroup(
            jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaida1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPSaida1Layout.createSequentialGroup()
                        .addGroup(jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLOpcoesFinalidade)
                            .addComponent(jLOpcoesNivel)
                            .addComponent(jCBCompactacao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLAjudaCompactacao))
                    .addGroup(jPSaida1Layout.createSequentialGroup()
                        .addComponent(jCBFinalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLAjudaConversao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSaida1Layout.createSequentialGroup()
                        .addComponent(jTFTamanhoArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLTamanhoArquivo1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPSaida1Layout.setVerticalGroup(
            jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaida1Layout.createSequentialGroup()
                .addComponent(jLOpcoesNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPSaida1Layout.createSequentialGroup()
                        .addComponent(jCBCompactacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLOpcoesFinalidade))
                    .addComponent(jLAjudaCompactacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBFinalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAjudaConversao))
                .addGap(18, 18, 18)
                .addGroup(jPSaida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFTamanhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTamanhoArquivo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPBProgresso.setStringPainted(true);

        jBCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        jBCancelar1.setText("Cancelar");
        jBCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelar1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Arquivo:");

        jLArquivos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLArquivos.setText("0/0");

        jLStatus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading.gif")));
        jLStatus1.setText("  ");
        jLStatus1.setToolTipText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLArquivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBJuntar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPSaida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPBProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(jLStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPSaida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBJuntar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLArquivos)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(330, 330, 330)
                    .addComponent(jLStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(390, Short.MAX_VALUE)))
        );

        jPEntrada.getAccessibleContext().setAccessibleName("Otimizar PDF em Lote");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAbrirDocumentoPDFEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirDocumentoPDFEntradaActionPerformed
        addFile(jTblListaPDF, jLStatus);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jBAbrirDocumentoPDFEntradaActionPerformed

    private void jBJuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBJuntarActionPerformed
        if (jTblListaPDF.getRowCount() > 1) {
            if (jRBSalvaDestinoInformado.isSelected() && !jTFSaidaPath.getText().isEmpty() || jRBSalvarPastaSeparada.isSelected()) {
                boolean erro = false;
                int rowCount = jTblListaPDF.getRowCount();
                Converter.arquivoAtual = 0;
                Converter.totalArquivos = rowCount;

                Utils.cleanTempFolder();
                for (int i = 0; i < rowCount; i++) {

                    String fileName = (String) jTblListaPDF.getValueAt(i, 0);
                    String local = "";
                    if (jRBSalvaDestinoInformado.isSelected()) {
                        local = jTFSaidaPath.getText() + "\\" + new File(fileName).getName();
                    } else {
                        local = fileName.substring(0, fileName.length() - 4) + "\\" + new File(fileName).getName();
                        File diretorio = new File(fileName.substring(0, fileName.length() - 4));
                        diretorio.mkdirs();
                    }

                    String output = Utils.removeMetadataFile(fileName);

                    float tamanhoArquivo = 0;
                    if (jCBFinalidade.getSelectedItem().toString().equals("Personalizado")) {
                        try {
                            tamanhoArquivo = Float.valueOf(jTFTamanhoArquivo.getText());
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "Por favor, digite um tamanho válido pro arquivo", "Atenção!", JOptionPane.ERROR_MESSAGE);
                            jTFTamanhoArquivo.grabFocus();

                            return;
                        }
                    }

                    String nivelCompactacao = NiveisCompactacao.getEnumByString((String) jCBCompactacao.getSelectedItem());
                    Integer finalidade = jCBFinalidade.getSelectedIndex();
                    ThreadConverter threadConverter = new ThreadConverter(
                            new Converter(output,
                                    local, nivelCompactacao, finalidade, tamanhoArquivo, new Integer(1), new Integer(Utils.getPageCount(output)), false), jPBProgresso, jLArquivos, jBJuntar, jBCancelar1);
                    executor.execute(threadConverter);

                    if (fileName.equals(jTFSaidaPath.getText())) {
                        erro = true;
                        break;
                    }

                }

            } else {
                JOptionPane.showMessageDialog(null, "Por favor, selecione o local onde deseja salvar o arquivo convertido", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione pelo menos 2 arquivos", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBJuntarActionPerformed

    private void jTblListaPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblListaPDFMouseClicked
        jTblListaPDFFocusGained(null);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jTblListaPDFMouseClicked

    private void jTblListaPDFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblListaPDFFocusGained
        controlarBotaoExcluir(jTblListaPDF, jBExcluirItemLista);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jTblListaPDFFocusGained

    private void jBExcluirItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirItemListaActionPerformed
        excluirDocumentoPDF(jTblListaPDF);
        jTblListaPDFFocusGained(null);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jBExcluirItemListaActionPerformed

    private void jTblListaPDFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblListaPDFFocusLost
        jTblListaPDFFocusGained(evt);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jTblListaPDFFocusLost

    private void jBLocalArmazenamentoArquivoSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLocalArmazenamentoArquivoSaidaActionPerformed
        JFileChooser fc = new JFileChooser(".");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int opt = fc.showSaveDialog(this);
        File f = fc.getSelectedFile();
        if (opt == 0) {
            jTFSaidaPath.setText(f.getPath());
        }
    }//GEN-LAST:event_jBLocalArmazenamentoArquivoSaidaActionPerformed

    private void jBDescerOrdemItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescerOrdemItemListaActionPerformed
        down(jTblListaPDF, jBDescerOrdemItemLista, jBSubirOrdemItemLista);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jBDescerOrdemItemListaActionPerformed

    private void jBSubirOrdemItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubirOrdemItemListaActionPerformed
        up(jTblListaPDF, jBDescerOrdemItemLista, jBSubirOrdemItemLista);
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jBSubirOrdemItemListaActionPerformed

    private void jTblListaPDFMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblListaPDFMouseReleased
        controlaBotaoOrdem(jBDescerOrdemItemLista, jBSubirOrdemItemLista, jTblListaPDF);
    }//GEN-LAST:event_jTblListaPDFMouseReleased

    private void jCBCompactacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCompactacaoActionPerformed

    }//GEN-LAST:event_jCBCompactacaoActionPerformed

    private void jCBFinalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFinalidadeActionPerformed
        jTFTamanhoArquivo.setVisible(jCBFinalidade.getSelectedIndex() == 2);
        jLTamanhoArquivo1.setVisible(jCBFinalidade.getSelectedIndex() == 2);
    }//GEN-LAST:event_jCBFinalidadeActionPerformed

    private void jLAjudaCompactacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAjudaCompactacaoMouseClicked

    }//GEN-LAST:event_jLAjudaCompactacaoMouseClicked

    private void jRBSalvarPastaSeparadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSalvarPastaSeparadaActionPerformed
        jTFSaidaPath.setVisible(false);
        jLSaidaInforme.setVisible(false);
        jBLocalArmazenamentoArquivoSaida.setVisible(false);
    }//GEN-LAST:event_jRBSalvarPastaSeparadaActionPerformed

    private void jRBSalvaDestinoInformadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSalvaDestinoInformadoActionPerformed
        jTFSaidaPath.setVisible(true);
        jLSaidaInforme.setVisible(true);
        jBLocalArmazenamentoArquivoSaida.setVisible(true);
    }//GEN-LAST:event_jRBSalvaDestinoInformadoActionPerformed

    private void jBCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelar1ActionPerformed
        Converter.cancelar = true;
    }//GEN-LAST:event_jBCancelar1ActionPerformed

    private void jTFTamanhoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTamanhoArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTamanhoArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtimizarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtimizarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtimizarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtimizarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OtimizarLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgroupTipoSaida;
    private javax.swing.JButton jBAbrirDocumentoPDFEntrada;
    private javax.swing.JButton jBCancelar1;
    private javax.swing.JButton jBDescerOrdemItemLista;
    private javax.swing.JButton jBExcluirItemLista;
    private javax.swing.JButton jBJuntar;
    private javax.swing.JButton jBLocalArmazenamentoArquivoSaida;
    private javax.swing.JButton jBSubirOrdemItemLista;
    private javax.swing.JComboBox jCBCompactacao;
    private javax.swing.JComboBox jCBFinalidade;
    private javax.swing.JLabel jLAjudaCompactacao;
    private javax.swing.JLabel jLAjudaConversao;
    private javax.swing.JLabel jLArquivos;
    private javax.swing.JLabel jLOpcoesFinalidade;
    private javax.swing.JLabel jLOpcoesNivel;
    private javax.swing.JLabel jLSaidaInforme;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLStatus1;
    private javax.swing.JLabel jLSuperior;
    private javax.swing.JLabel jLTamanhoArquivo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblTextoSelecionePDF;
    private javax.swing.JProgressBar jPBProgresso;
    private javax.swing.JPanel jPEntrada;
    private javax.swing.JPanel jPSaida;
    private javax.swing.JPanel jPSaida1;
    private javax.swing.JRadioButton jRBSalvaDestinoInformado;
    private javax.swing.JRadioButton jRBSalvarPastaSeparada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFSaidaPath;
    private javax.swing.JTextField jTFTamanhoArquivo;
    private javax.swing.JTable jTblListaPDF;
    // End of variables declaration//GEN-END:variables

    void iniciarArgumentos(List<String> listaArquivos) {
        for (String arq : listaArquivos) {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel = (DefaultTableModel) jTblListaPDF.getModel();
            String pageCount = String.valueOf(Utils.getPageCount(arq));
            if (!pageCount.equals("0")) {
                tableModel.addRow(new Object[]{arq, pageCount});
            }
        }
        this.setVisible(true);
    }

    private void setPreferencias() {
        if (Preferences.isTamanhoDefinido()) {
            jCBFinalidade.setSelectedItem("Personalizado");
            jTFTamanhoArquivo.setText(String.valueOf(Preferences.getSizeArquivo()));
        }

    }

}
